# Generated by Django 5.2.3 on 2025-06-12 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useruths', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
