name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Guardar clave privada EC2
      run: |
        echo "${{ secrets.EC2_KEY }}" > key.pem
        chmod 400 key.pem

    - name: Subir archivos al servidor EC2
      run: |
        rsync -avz --delete \
          -e "ssh -o StrictHostKeyChecking=no -i key.pem" \
          ./ ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/${{ secrets.EC2_USER }}/miapp/

    - name: Ejecutar Docker Compose en EC2
      run: |
        ssh -i key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          cd miapp
          docker-compose down || true
          docker-compose up -d --build
        EOF
